app/Http/routes.php
    Route::get('emailtemplate/create', array('as' => 'newemailtemplate', 'uses' => 'EmailTemplatesController@create'));
    Route::get('emailtemplate/edit/{etemplate}', array('as' => 'emailtempalte.edit', 'uses' => 'EmailTemplatesController@edit'));
    //Route::get('emailtemplate/update/{etemplate}', array('as' => 'emailtempalte.update', 'uses' => 'EmailTemplatesController@update'));
    Route::post('emailtemplate/update/{etemplate}', array('as' => 'emailtempalte.update', 'uses' => 'EmailTemplatesController@update'));
    Route::get('emailtemplate/store', array('as' => 'storemailtemplate', 'uses' => 'EmailTemplatesController@storeemailtemplate'));
    Route::post('emailtemplate/store', array('as' => 'storemailtemplate', 'uses' => 'EmailTemplatesController@storeemailtemplate'));
	//Route::get('AddSubscription/storeSubscription', array('as' => 'newSubscription', 'uses' => 'AddSubscriptionController@storeStaff'));
	Route::resource('emailtemplates', 'EmailTemplatesController');
    
	// OMS staff
    Route::get('staff', array('as' => 'staff', 'uses'=>'OmsStaffsController@index'));
	Route::get('ajaxOmsStaff', 'OmsStaffsController@postAjax');
	Route::post('ajaxOmsStaff', 'OmsStaffsController@postAjax');
    //
	Route::get('staff', array('as' => 'staff', 'uses' => 'OmsStaffsController@index'));
	Route::get('staff/create', array('as' => 'newstaff', 'uses' => 'OmsStaffsController@create'));
	//Route::get('ajaxOmsStaff', 'OmsStaffsControllerr@postAjax');
	//Route::post('ajaxOmsStaff', 'OmsStaffsController@postAjax');
	Route::get('staff/storeStaff', 'OmsStaffsController@store');
	Route::post('staff/storeStaff', 'OmsStaffsController@store');
	Route::get('staff/search', array('as' => 'ssearch', 'uses' => 'OmsStaffsController@search'));
	Route::get('staff/edit/{staff}', array('as' => 'ostaff.edit', 'uses' => 'OmsStaffsController@editOmsStaff'));
	//Route::get('staff/update/{staff}',  'OmsStaffsController@update');
	Route::any('staff/update/{staff}', array('as' => 'staff.update', 'uses' => 'OmsStaffsController@update'));
	Route::get('omsstaffs/search', array('as' => 'sasearch', 'uses' => 'OmsStaffsController@searchstaffnonactive'));
	Route::get('staff/details/{staff}', array('as' => 'staff.details', 'uses' => 'OmsStaffsController@details'));
	Route::resource('staff', 'OmsStaffsController');

//  subscription route section
    Route::get('subscriptions', array('as' => 'subscriptions', 'uses'=>'SubscriptionsController@index'));
	Route::get('ajaxSubscriptions', 'SubscriptionsController@postAjax');
	Route::post('ajaxSubscriptions', 'SubscriptionsController@postAjax');
	Route::get('subscriptions/create', array('as' => 'newsubscription', 'uses' => 'SubscriptionsController@create'));
    Route::post('subscriptions/store', 'SubscriptionsController@store');
    Route::get('subscriptions/search', 'SubscriptionsController@searchsubscription');
    Route::get('subscriptions/edit/{subscription}', array('as' => 'subscriptions.edit', 'uses' => 'SubscriptionsController@edit'));
	Route::put('subscriptions/update/{subscription}', array('as' => 'subscriptions.update', 'uses' => 'SubscriptionsController@update'));
    
    #Route::post('subscriptions/storepaymentadjustment', 'SubscriptionsController@storepaymentadjustment');
    
    //company subscription section
    Route::get('companysubscribed', array('as' => 'csubscriptions', 'uses'=>'CompanySubscriptionController@index'));
    Route::get('companysubscribedSearch', 'CompanySubscriptionController@search');
    Route::post('ajaxCompanySubscribed', 'CompanySubscriptionController@postAjax');
    Route::resource('companysubscribed', 'CompanySubscriptionController');
    //company subscription section end here
    
//    
	Route::get('fields', array('as' => 'fields', 'uses' => 'FieldsController@index'));
	Route::get('ajaxFields', 'FieldsController@postAjax');
	Route::post('ajaxFields', 'FieldsController@postAjax');	
	Route::get('fields/create', array('as' => 'createtplfield', 'uses' => 'FieldsController@create'));
	Route::resource('fields', 'FieldsController');
	
	
	
	
	Route::get('sheetfields', array('as' => 'sheetfields', 'uses' => 'CompanySheetFieldsController@index'));
	Route::get('ajaxSheetFields', 'CompanySheetFieldsController@postAjax');
	Route::post('ajaxSheetFields', 'CompanySheetFieldsController@postAjax');
	Route::get('sheetfields/create', array('as' => 'createsheetfield', 'uses' => 'CompanySheetFieldsController@create'));
	Route::resource('sheetfields', 'CompanySheetFieldsController');
	
	
	
	//Public portal
	Route::get('publicportal', array('as' => 'publicPortal', 'uses' => 'HomeController@publicPortal'));
	
	// company Portal
	//Route::get('companyportal', array('as' => 'companyPortal', 'uses' => 'HomeController@companyPortal'));
    Route::get('companyportal', array('as' => 'company.Portal', 'uses' => 'CompanyPortalController@index'));
    Route::any('companyportal/edit/{company}', array('as' => 'companyPortal.edit', 'uses' => 'CompanyPortalController@edit'));
    Route::put('companyportal/update/{company}', array('as' => 'companyPortal.update', 'uses' => 'CompanyPortalController@update'));
	Route::get('companyportal/companytools', array('as' => 'cTools', 'uses' => 'ComCompanyToolsController@index'));
    Route::get('companyportal/details/{company}', array('as' => 'companyportal.details', 'uses' => 'CompanyPortalController@details'));
	Route::get('cCompanytools', array('as' => 'cCompanytools', 'uses' => 'ComCompanyToolsController@index'));
	Route::get('ajaxcCompanytools', 'ComCompanyToolsController@postAjax');
	Route::post('ajaxcCompanytools', 'ComCompanyToolsController@postAjax');

// Company Route Section
	
	Route::get('company','CompanyController@index');
	Route::get('company', array('as'=>'company', 'uses' => 'CompanyController@index'));
	Route::get('company/create', array('as' => 'newcompany', 'uses' => 'CompanyController@create'));
	Route::post('ajaxCompany', 'CompanyController@postAjax');
	Route::get('company/details/{company}', array('as' => 'company.details', 'uses' => 'CompanyController@details'));
	Route::get('company/search', array('as' => 'csearch', 'uses' => 'CompanyController@search'));
	Route::get('csearch', 'CompanyController@search');
	Route::get('company/edit/{company}', array('as' => 'company.edit', 'uses' => 'CompanyController@edit'));
	#Route::post('company/create', ['as' => 'newcompany_store', 'uses' => 'CompanyController@store']);
	Route::put('company/update/{company}', array('as' => 'company.update', 'uses' => 'CompanyController@update'));
	Route::post('company/store', 'CompanyController@store');
//		
// Routs section for company portal
	
	// Company portal client Section 
	//Route::get('companyportal/clients', array('as' => 'companyPortal', 'uses' => 'CompanyClientController@index'));
	Route::get('companyportal/clients', array('as' => 'Cpclient', 'uses' => 'CompanyClientController@index'));
	Route::get('companyportal/client/details/{client}', array('as' => 'cpclients.details', 'uses' => 'CompanyClientController@details'));
    Route::get('companyportal/client/edit/{company}', array('as' => 'companyclient.edit', 'uses' => 'CompanyClientController@edit'));
    Route::any('companyportal/client/update/{company}', array('as' => 'companyclient.update', 'uses' => 'CompanyClientController@update'));
    //Route::post('companyportal/client/update/{company}', array('as' => 'companyclient.update', 'uses' => 'CompanyClientController@update'));
	Route::get('ajaxCompanyPortalClient', 'CompanyClientController@postAjax');
	Route::post('ajaxCompanyPortalClient', 'CompanyClientController@postAjax');
    Route::get('companyClientSearch','CompanyClientController@search');
	Route::get('companyportal/client/create', array('as' => 'companynewclient', 'uses' => 'CompanyClientController@create'));
    Route::get('companyportal/clients/store', array('as' => 'companystoreclient', 'uses' => 'CompanyClientController@store'));
    Route::post('companyportal/clients/store', array('as' => 'companystoreclient', 'uses' => 'CompanyClientController@store'));
	Route::controller('companyportal/clients', 'CompanyClientController');
	
    // Comapny portal staff section routes
    Route::get('companyportal/staff', array('as' => 'Cpstaff', 'uses' => 'CompanyStaffController@index'));
    Route::get('companyportal/staffcreate', array('as' => 'newcpstaff', 'uses' => 'CompanyStaffController@create'));
    Route::get('companyportal/storeStaff', 'CompanyStaffController@storeCompanyPortalStaff');
	Route::post('companyportal/storeStaff', 'CompanyStaffController@storeCompanyPortalStaff');
    Route::get('companyportal/staff/edit/{staff}', array('as' => 'Cpstaff.edit', 'uses' => 'CompanyStaffController@editCompanyPortalStaff'));
    Route::any('companyportal/staff/update/{staff}', array('as' => 'Cpstaff.update', 'uses' => 'CompanyStaffController@updateStaff'));
    Route::get('ajaxCompanyPortalStaff', 'CompanyStaffController@postAjax');
	Route::post('ajaxCompanyPortalStaff', 'CompanyStaffController@postAjax');
    Route::controller('companyportal/staff', 'CompanyStaffController');
    
	// Company portal template Section 
	Route::get('companyportal/templates', array('as' => 'companyTemplate', 'uses' => 'CompanyTemplatesController@index'));
	#Route::get('companyportal/clients', array('as' => 'Cpclient', 'uses' => 'CompanyClientController@index'));
	Route::get('companyportal/templates/details/{template}', array('as' => 'cptemplates.details', 'uses' => 'CompanyTemplatesController@details'));
	Route::get('companyportal/templates/edit/{template}', array('as' => 'cptemplates.edit', 'uses' => 'CompanyTemplatesController@edit'));
    Route::get('companyportal/templates/create', array('as' => 'newcptemplate', 'uses' => 'CompanyTemplatesController@create'));
    Route::post('companyportal/templates/store', 'CompanyTemplatesController@store');
    Route::put('companyportal/templates/update/{template}', array('as' => 'cptemplates.update', 'uses' => 'CompanyTemplatesController@update'));

resources/views/companysubscription/actions.blade.php
@if($company_status!='Active' && $company_status!='Terminated')
<button class="btn btn-warning btn-sm approveSubscribedCompany" data-id={{$id}} data-status="Active" data-show="Approve" data-route="approveCompanySubscription" data-path="CompanySubscribed" type="button" data-_token={{csrf_token()}}>
    Approve</button>
<button class="btn btn-warning btn-sm approveSubscribedCompany" data-id={{$id}} data-status="Terminated" data-show="UnApprove" data-route="approveCompanySubscription" data-path="CompanySubscribed" type="button" data-_token={{csrf_token()}}>
UnApprove</button>
@else {{'Approved'}}
@endif

resources/views/companysubscription/details.blade.php
@extends('app')

@section('style')
	{{--<link href="{{ asset('/vendor/mjolnic-bootstrap-colorpicker/dist/css/bootstrap-colorpicker.min.css') }}" rel="stylesheet">--}}
	<link href="{{ asset('/css/spectrum.css') }}" rel="stylesheet">
	<link href="{{ asset('/vendor/bootstrap-table/src/extensions/reorder-rows/bootstrap-table-reorder-rows.css') }}" rel="stylesheet">
@stop

@section('script')
<!-- Page-Level Plugin Scripts -->
   	<script src="{{ asset('/js/templates/templates.js') }}"></script>   
   	{{--<script src="{{ asset('/vendor/mjolnic-bootstrap-colorpicker/dist/js/bootstrap-colorpicker.min.js') }}"></script>--}}
	<script src="{{ asset('/js/spectrum.js') }}"></script>
   	<script src="{{ asset('/js/templates/fields.js') }}"></script>   
   	<script src="{{ asset('/vendor/TableDnD/dist/jquery.tablednd.js') }}"></script>
	<script src="{{ asset('/vendor/bootstrap-table/src/extensions/reorder-rows/bootstrap-table-reorder-rows.js') }}"></script>   
@stop

@section('content')
<div class="panel panel-info">
  <div class="panel-heading">		  	
		<div class="container">
			<h4 class="panel-title pull-left"><i class="glyphicon glyphicon-info-sign"></i> Template Details </h4>	
			<a href="{{route('templates')}}" class="btn btn-default  btn-xs pull-right" role="button">Back to Templates</a>	
		</div>		  	
  </div>
  <div class="panel-body">
		
		  <ul class="nav nav-tabs" role="tablist">
		       <li class="active"><a href="#core_details" data-toggle="tab">Core Details</a></li>
		       <li><a href="#fields" aria-controls="fields" role="tab" data-toggle="tab" id="lfields" data-tpl="{{$template->id}}">Fields</a></li>
		  </ul>
			
		<!-- Tab panes -->
	    <div class="tab-content">
	        <div class="tab-pane active" id="core_details">
	            <div class="row">
	                <div class="col-lg-6">
	                    <div class="top10">                 
	                       <button class="btn btn-danger btn-sm templateDelete pull-right left10" role='button' data-id="{{$template->id}}" data-_token="{!!csrf_token()!!}" >Delete</button>	                        			                        
	                       <a href="{!!route('templates.edit', array('template' => $template->id)) !!}" class="btn btn-warning btn-sm pull-right " role='button' >Edit</a>
	                    </div>
	                </div>
	            </div>
	            <div class="row">
	                <div class="col-lg-8 col-lg-offset-1">
	                    <div class="row">
	                        <div class="col-lg-7">	                          
                     	    		<div class="row detail-cell">
			                        	<div class="col-lg-6"><p class = "detail-cell-label">Template Name</p></div>
			                        	<div class="col-lg-6"><p>{{$template->name}}</p></div>     
			                        </div>
			                        
			                        <div class="row detail-cell">
			                        	<div class="col-lg-6"><p class = "detail-cell-label">Template Purpose</p></div>
			                        	<div class="col-lg-6"><p>{{$template->purpose}}</p></div>     
			                        </div>
			                        
			                        <div class="row detail-cell">
			                        	<div class="col-lg-6"><p class = "detail-cell-label">Client Fields to Include</p></div>
			                        	<div class="col-lg-6">			                        	
			                        		@if(!empty($temIncludeFields) && in_array('first_name', $temIncludeFields))	
			                        			<p>First Name</p>
			                        		@endif			
			                        		@if(!empty($temIncludeFields) && in_array('last_name', $temIncludeFields))	
			                        			<p>Last Name</p>
			                        		@endif
			                        	</div>	
			                        </div>
			                       
			                        <div class="row detail-cell">
			                        	<div class="col-lg-6"><p class = "detail-cell-label">Client Fields to Include</p></div>
			                        	<div class="col-lg-6">			                        	
			                        		@if(!empty($temIncludeFields))			                        		
			                        			@foreach($trans_labels as $key=>$field)
			                        				@if(in_array($key, $temIncludeFields))	
			                        					<p>{{$field}}</p>
			                        				@endif
			                        			@endforeach			                        		
			                        		@endif						                        		
			                        	</div>	
			                        </div>
			                      
			                      	<div class="row detail-cell">
			                        	<div class="col-lg-6"><p class = "detail-cell-label"># Rows to Freeze </p></div>
			                        	<div class="col-lg-6"><p>{{$template->rows_to_freeze}}</p></div>     
			                        </div>
			                       
			                        <div class="row detail-cell">
			                        	<div class="col-lg-6"><p class = "detail-cell-label"># Freeze First Column </p></div>
			                        	<div class="col-lg-6"><p>@if($template->freeze_first_column==1) Yes @else No @endif</p></div>     
			                        </div>
			                        	
			                        	 
			                     	<div class="row detail-cell">
			                        	<div class="col-lg-6"><p class = "detail-cell-label">Users Who Can Access Sheet</p></div>
			                        	<div class="col-lg-6">
			                        	
			                        		@if($template->all_user_accsess==1)
			                        				<p>All company users</p>
			                        		@elseif(!empty($user_access))			                        		
			                        			@foreach($user_access as $username)			                        					
			                        					<p>{{$username}}</p>			                        				
			                        			@endforeach			                        		
			                        		@endif	
			                        	</div>     
			                        </div>  
			                      	<div class="row detail-cell">
			                        	<div class="col-lg-6"><p class = "detail-cell-label">Column Order</p></div>
			                        	<div class="col-lg-6"><p>{{$column_order[$template->column_order]}}</p></div>     
			                        </div>  
			                        <div class="row detail-cell">
			                        	<div class="col-lg-6"><p class = "detail-cell-label">Status</p></div>
			                        	<div class="col-lg-6"><p>{{$template->status}}</p></div>     
			                        </div>                         
	                        </div>
	                    </div>
	                </div>
	            </div>
	            <div class="row">
	                <div class="col-lg-6">
	                    <div class="top10">                      
	                        <button class="btn btn-danger btn-sm templateDelete pull-right left10" role='button' data-id="{{$template->id}}" data-_token="{!!csrf_token()!!}" >Delete</button>	                        			                        
	                       <a href="{!!route('templates.edit', array('template' => $template->id)) !!}" class="btn btn-warning btn-sm pull-right " role='button' >Edit</a>
	                    </div>
	                </div>
	            </div>	            
	        </div>
	        <div role="tabpanel" class="tab-pane fade" id="fields">
	        	<div class="container top20">
                        <div class="panel panel-info" id="fields-div">  			  		  			 
                            <div class="panel-body">
                            	<div class="container bottom20">
						        	<div class="row">
						        		{!! Form::button('<i class="fa fa-plus"></i> Add Field', array('class'=>'btn btn-xs  btn-info pull-right ajax',  'data-template_id'=>$template->id, 'data-route' => 'createField', 'data-target' => '#newfield-div', 'data-path' => 'Fields', 'data-_token'=>csrf_token()))!!}
						        	</div>		
						        </div>	        
							    <div class="container datalist">	                               
	                                    <div id="list">
	                                        <table class="fieldtable" data-pagination="false" data-search="true" data-sort-name="priority_order" data-sort-order="asc" >
	                                            <thead>
	                                                <tr>	                                                
	                                                	<th data-field="id" data-visible="false">Id</th>
	                                                    <th data-field="field_name" >Name</th>
	                                                    <th data-field="type" >Type</th>
	                                                    <th data-field="tooltip">Tooltip</th>
	                                                    <th data-field="priority_order" >Priority Order</th>		                                                       
	                                                    <th data-field="status" >Status</th>   
	                                                    <th data-field="actions">Actions</th>
	                                                </tr>
	                                            </thead>                                           
	                                        </table>
	                                    </div>
	                                </div>                                   	
                            </div>
                        </div>                                                
                        <div class="panel panel-info"  id="newfield-div" style="display:none"></div>
			 			<div class="panel panel-info"  id="editfield-div" style="display:none"></div>			 
                    </div>
             </div>       
	    </div>		
  </div>
</div>
    
    <input type="hidden" id="data-ajax" value="fields">
    {!!Form::hidden('template_id', $template->id, array('class'=>'template_id'))!!}    
    {!! Form::token() !!}
@stop

resources/views/companysubscription/index.blade.php
@extends('app')
@section('style')
	<link href="{{ asset('/vendor/eonasdan-bootstrap-datetimepicker/build/css/bootstrap-datetimepicker.min.css') }}" rel="stylesheet">	
	<link href="{{ asset('/vendor/jquery-ui/themes/cupertino/jquery-ui.min.css') }}" rel="stylesheet">
@stop

@section('script')
<script>var tableData = {!! $tableData !!};</script>
<script src="{{ asset('/vendor/moment/min/moment.min.js') }}"></script> 
<script src="https://code.jquery.com/ui/1.11.4/jquery-ui.min.js"></script>
<script src="{{ asset('/js/typeahead.js-master/dist/typeahead.jquery.js') }}"></script>
<script src="{{ asset('/vendor/eonasdan-bootstrap-datetimepicker/build/js/bootstrap-datetimepicker.min.js') }}"></script>   
<script src="{{ asset('/js/jquery.mask.js') }}"></script>   
<script src="{{ asset('/js/company/company.js') }}"></script>
 
@endsection

@section('content')
<div class="container">
    <div class="row">    
        <div class="col-md-12">
        	<div class="panel panel-info">
				<div class="panel-heading">		  	
					<div class="container">			
						<div class="row">
							<h4 class="panel-title pull-left"><i class="glyphicon glyphicon-user"></i>Company Subscribed </h4>	  			 
				  		</div>
				  	</div>
				</div>		
				  <div class="panel-body">
				    <div class="container datalist">
                        {!! Form::open( array('staffsearch' => 'form', 'method' => 'put', 'files'=>true, 'class'=>'form-horizontal form-companysubscription-search',  'autocomplete'=>"off")) !!} 
				    	<div class="search-radio-btn pull-left">
                              <div class="input-field"> {!! Form::radio('staffstatus', 'Active', true, ['class' => 'left10 right10','id' => 'staffstatus']) !!} New / Approved</div>            
                              <div class="input-field"> {!! Form::radio('staffstatus', 'NonActive', null, ['class' => 'left10 right10','id' => 'staffstatus']) !!} UnApproved</div>
                              <div class="input-field"> {!! Form::submit('Search', array('class'=>'btn btn-xs btn-info', 'data-path'=>'Staffs','data-route' => 'searchstaff','data-_token'=>csrf_token()))!!}</div>
                        </div>
                        {!! Form::close() !!}
						<div id="list">
							 <table class="data-table" data-toggle="table" data-pagination="true" data-search="true" data-sort-name="clname" data-sort-order="asc" >
			                    <thead>
			                        <tr>
                                        <th data-field="company_number" data-sortable="true">Company Number</th>
			                            <th data-field="company_name" data-sortable="true">Company Name</th>                                        
                                         <th data-field="primary_contact" data-sortable="true">Primary Contact Name</th>
                                         <th data-field="email" data-sortable="true">Email</th>
			                            <th data-field="primary_phone" data-sortable="true">Contact(Phone No)</th>		                                                       
                                        <th data-field="status" data-sortable="true">Status</th>
			                            <th data-field="actions">Actions</th>
			                        </tr>
			                    </thead>
			                    <tbody>
			                    </tbody>
			                </table>
						</div>
					</div>   	
				  </div>
			</div>
          
            </div>

        </div>
    </div>
    <input type="hidden" id="data-ajax" value="templates">
@endsection

resources/views/companysubscription/searchactions.blade.php
<?php if($company_status == 'Active' && $isDeleted == 0) { ?>
{{'Approved'}}
<?php 
} else if($company_status != 'Active' && $company_status != 'Terminated' && $isDeleted == 0) { ?>
<button class="btn btn-warning btn-sm approveSubscribedCompany" data-id={{$id}} data-status="Active" data-show="Approve" data-route="approveCompanySubscription" data-path="CompanySubscribed" type="button" data-_token={{csrf_token()}}>
    Approve</button>
<button class="btn btn-warning btn-sm approveSubscribedCompany" data-id={{$id}} data-status="Terminated" data-show="UnApprove" data-route="approveCompanySubscription" data-path="CompanySubscribed" type="button" data-_token={{csrf_token()}}>
UnApprove</button>
<?php } else if($isDeleted) { ?>
<a href="#" id="" class="btn  btn-sm  btn-danger resetcompanyunapproved" data-id="{{$id}}" data-item="{{$id}}" data-route="resetcompanyunapproved" data-path="CompanySubscribed" data-_token="{{csrf_token()}}">ReCall</a>
<?php } ?>